# -*- coding: utf-8 -*-
"""Round2EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDW_5XjwjtPjnXQ-RSa_jnvxHtor_Ct5
"""

import pandas as pd

df = pd.read_csv("Q18_box_office.csv")

df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()

df.describe()

import matplotlib.pyplot as plt

plt.scatter(df['screen_count'], df['opening_weekend_revenue_crore'])

plt.xlabel('Screen Count')
plt.ylabel('Opening Weekend Revenue (Crore)')
plt.title('Screen Count vs Opening Revenue')

plt.show()

df.groupby('genre')['opening_weekend_revenue_crore'].mean().plot(kind='bar')

plt.xlabel('Genre')
plt.ylabel('Average Opening Revenue (Crore)')
plt.title('Genre vs Average Opening Revenue')

plt.show()

df[['production_budget_crore', 'screen_count', 'opening_weekend_revenue_crore']].corr()

# Calculate revenue per screen
df['revenue_per_screen'] = (
    df['opening_weekend_revenue_crore'] / df['screen_count']
)

print("Revenue Per Screen:")
print(df[['title', 'revenue_per_screen']].head())

# Create budget categories
df['budget_category'] = pd.cut(
    df['production_budget_crore'],
    bins=[0, 50, 150, float('inf')],
    labels=['Low', 'Medium', 'High']
)

print("\nBudget Categories:")
print(df[['title', 'production_budget_crore', 'budget_category']].head())

# Average opening revenue by budget category
print("\nAverage Revenue by Budget Category:")
print(
    df.groupby('budget_category', observed=True)
      ['opening_weekend_revenue_crore']
      .mean()
)

# Compare revenue per screen by genre
print("\nAverage Revenue Per Screen by Genre:")
print(
    df.groupby('genre')['revenue_per_screen']
      .mean()
      .sort_values(ascending=False)
)

# Find correlation with opening revenue
correlation = df[
    ['production_budget_crore',
     'screen_count',
     'opening_weekend_revenue_crore']
].corr()['opening_weekend_revenue_crore']

print("\nCorrelation with Opening Revenue:")
print(correlation.sort_values(ascending=False))